//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oxyplot_teplo.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ICulcService")]
    public interface ICulcService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICulcService/CulcTeploParal", ReplyAction="http://tempuri.org/ICulcService/CulcTeploParalResponse")]
        Teplo_WCF_Library.OutputDate CulcTeploParal(Teplo_WCF_Library.InputDate inputMatrixes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICulcService/CulcTeploParal", ReplyAction="http://tempuri.org/ICulcService/CulcTeploParalResponse")]
        System.Threading.Tasks.Task<Teplo_WCF_Library.OutputDate> CulcTeploParalAsync(Teplo_WCF_Library.InputDate inputMatrixes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICulcService/CulcTeploPosl", ReplyAction="http://tempuri.org/ICulcService/CulcTeploPoslResponse")]
        Teplo_WCF_Library.OutputDate CulcTeploPosl(Teplo_WCF_Library.InputDate inputMatrixes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICulcService/CulcTeploPosl", ReplyAction="http://tempuri.org/ICulcService/CulcTeploPoslResponse")]
        System.Threading.Tasks.Task<Teplo_WCF_Library.OutputDate> CulcTeploPoslAsync(Teplo_WCF_Library.InputDate inputMatrixes);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICulcServiceChannel : Oxyplot_teplo.ServiceReference1.ICulcService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CulcServiceClient : System.ServiceModel.ClientBase<Oxyplot_teplo.ServiceReference1.ICulcService>, Oxyplot_teplo.ServiceReference1.ICulcService {
        
        public CulcServiceClient() {
        }
        
        public CulcServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CulcServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CulcServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CulcServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Teplo_WCF_Library.OutputDate CulcTeploParal(Teplo_WCF_Library.InputDate inputMatrixes) {
            return base.Channel.CulcTeploParal(inputMatrixes);
        }
        
        public System.Threading.Tasks.Task<Teplo_WCF_Library.OutputDate> CulcTeploParalAsync(Teplo_WCF_Library.InputDate inputMatrixes) {
            return base.Channel.CulcTeploParalAsync(inputMatrixes);
        }
        
        public Teplo_WCF_Library.OutputDate CulcTeploPosl(Teplo_WCF_Library.InputDate inputMatrixes) {
            return base.Channel.CulcTeploPosl(inputMatrixes);
        }
        
        public System.Threading.Tasks.Task<Teplo_WCF_Library.OutputDate> CulcTeploPoslAsync(Teplo_WCF_Library.InputDate inputMatrixes) {
            return base.Channel.CulcTeploPoslAsync(inputMatrixes);
        }
    }
}
